
eureka:
  client:
    healthcheck:
      enabled: true  # 开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    lease-renewal-interval-in-seconds: 20  #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 60 # 续约到期时间（默认90秒）

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sq_users?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: sqzn
    password: sqzn
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1


